### ISSUE TITLE
Whispering Root tracker

### ISSUE THREAD

**Issue by Zamiell** [ReznoRMichael/hollow-knight-completion-check#7]
Right now the site just tracks X/15 Whispering Roots. But you don't know which ones are remaining, so this is very frustrating.

This is a feature request for the site to track the individual Whispering Roots and which ones are remaining to be "activated" / finished.

**Comment by ReznoRMichael** [comment]
Every Whispering Root is now visible in the Analyzer since v2.0.0 👍 (along many other Collectibles)

**Comment by Zamiell** [comment]
Thank you!!
