### ISSUE TITLE
X on 100% True Completion

### ISSUE THREAD

**Issue by Araraura** [ReznoRMichael/hollow-knight-completion-check#8]
Hey, the True Completion % shows an X instead of a V even when it's 100% completed.

![2022-01-14 20_09_29-Window](https://user-images.githubusercontent.com/25017422/149564287-d305ee2b-0e2f-4b38-84e0-8330d0011ff1.png)

[user1.zip](https://github.com/ReznoRMichael/hollow-knight-completion-check/files/7872359/user1.zip)

**Comment by ReznoRMichael** [comment]
Thanks for the info and sharing this incredible save file! I'll look into it 👍 I'm now curious myself what went wrong there.
